# Only one output_plugin can be defined at a time.
# This plugin is called to filter the output of the final CSS.
output_plugin:
  class: \Xazure\Css\Plugin\BeautifyPlugin
  mode: expanded # expanded, compact, or minified - Affects the whitespace in output, going from more whitespace to less.

# Any plugins can be loaded here.
# Plugins have a wide variety of settings.
# All plugins should at least define a class. Any other settings are
# dictated by the plugin itself.
plugins:
  xazure.css.plugin.atvar:
    class: \Xazure\Css\Plugin\AtVarPlugin
  xazure.css.plugin.noprefix:
    class: \Xazure\Css\Plugin\NoPrefix\NoPrefixPlugin
    # An array of properties to exclude.
    # If present, all properties but those in exclude are used.
    # exclude: [border-radius, ...]

    # An array of properties to include.
    # If present, only properties in the array are used.
    # include: [border-radius, ...]

    # If exclude and include are both present, they are both ignored and all are allowed.

    # An array of browsers and their minimum version to include for.
    # If a browser is on the list, that version is used instead of the default.
    # If you want to completely omit support for a browser, set the version to "-1".
    # browsers: { ie: 7, ff: 10, omini: -1 }
    # Browsers supported are (default version in ()):
    # - Internet Explorer: ie(7)
    # - Firefox: ff(15)
    # - Chrome: chrome(22)
    # - Opera: opera(12.1)
    # - Opera Mini: omini(5.0)
    # - Safari: safari(5.1)
    # - Android: android(2.1)
    # - Blackberry: bb(7.0)
    # - iOS Safari: ios(3.2)

    # By default, it will try all properties it is capable of user.

    # Defines new Property classes outside of the defaults.
    # properties:
    # some-property: Some\Class
    #
    # These are loaded directly as properties, so they can override default properties
    # as well as fill in gaps for missing properties.
    # They must implement Property\PropertyInterface relative to NoPrefixPlugin's namespace.